apiVersion: v2
name: guacamole
description: Apache Guacamole (guacd + guacamole + postgres)
type: application
version: 0.5.0
appVersion: "1.6.0"
icon: https://guacamole.apache.org/images/guacamole-logo.png
