externalPostgres:
  host: "pg-postgresql.db.svc.cluster.local"
  port: 5432
  db: "guacamole"
  user: "guacamole"
  existingSecret:
    name: "guacamole"
    key: "database-password"

guacd:
  replicaCount: 1

guacamole:
  replicaCount: 1
  env:
    guacdPort: 4822
    guacdSsl: "false"

service:
  guacamole:
    port: 8080
  guacd:
    port: 4822

ingress:
  enabled: true
  className: "nginx"
  host: guacamole.local
  path: /guacamole
  pathType: Prefix

  annotations: 
    cert-manager.io/cluster-issuer: lab-selfsigned
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

  tls:
    enabled: false
    secretName: ""

certManager:
  enabled: true
  issuerRef:
    kind: ClusterIssuer
    name: lab-selfsigned
  dnsNames:
    - guacamole.local

externalSecrets:
  enabled: false

openid:
  enable: disable
  endpoint: "https://authentik.local" 
  jwks_endpoint: "https://authentik.local/jwks"
  issuer: "iauthentik" 
  client_id: "id_cliente_falso"
  redirect_uri: "https://authentik.local/returngaucamole"
  extension_priority: "*, openid"  
