apiVersion: v1
kind: Service
metadata:
  name: guacamole
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.guacamole.port }}
      targetPort: http
  selector:
    app.kubernetes.io/component: guacamole
    {{- include "guacamole.selectorLabels" . | nindent 4 }}
