apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "guacamole.fullname" . }}-guacd
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.guacd.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: guacd
      {{- include "guacamole.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: guacd
        {{- include "guacamole.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: guacd
          image: "{{ .Values.images.guacd.repository }}:{{ .Values.images.guacd.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: guacd
              containerPort: 4822
          args:
            - "-f"
            - "-b"
            - "0.0.0.0"
            - "-L"
            - "info"
          readinessProbe:
            tcpSocket:
              port: guacd
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
