{{- if and .Values.externalSecrets (eq (.Values.externalSecrets.enabled | default false) true) }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "guacamole.fullname" . }}-secrets
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | quote }}
    name: {{ .Values.externalSecrets.secretStoreRef.name | quote }}
  target:
    name: {{ .Values.externalSecrets.target.name | quote }}
    creationPolicy: {{ .Values.externalSecrets.target.creationPolicy }}
    deletionPolicy: {{ .Values.externalSecrets.target.deletionPolicy }}
    template:
      type: {{ .Values.externalSecrets.target.type | quote }}
  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.dataFrom.remoteKey | quote }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}